<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Kispest SE pálya foglalás</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="foglalas.php">Új foglalás</a></li>
                <li><a href="foglalasaim.php">Foglalásaim</a></li>
                <li><a href="adataim.php">Adataim</a></li>
                <li><a href="kilepes.php">Kilépés</a></li>
            </ul>
        </div>
    </div>
</nav>