        <div id="notification-wrapper"></div>

        <div id="spinner-wrapper">
            <div class="spinner">
                <div class="spinner-container container1">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                </div>
                <div class="spinner-container container2">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                </div>
                <div class="spinner-container container3">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                </div>
            </div>
        </div>
        <script src="lib/jquery.min.js"></script>
        <script src="lib/underscore.min.js"></script>
        <script src="lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="lib/moment.min.js"></script>
        <script src="lib/moment.hu.js"></script>
        <script src="lib/numeral.min.js"></script>
        <script src="lib/numeral.hu.min.js"></script>
        <script src="lib/datepicker/js/bootstrap-datepicker.min.js"></script>
        <script src="lib/datepicker/locales/bootstrap-datepicker.hu.min.js"></script>
        <script src="js/login.js"></script>
        <script src="js/profiledata.js"></script>
        <script src="js/reservation.js"></script>
        <script src="js/reservations.js"></script>
        <script src="js/activation.js"></script>
        <script src="js/checkout.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>